version : "3.7"
services :
  proyectos-monolito :
    container_name : proyectos-micro
    image : proyectos-micro:v1
    build:
      context: .
    ports : 
      - "3001:3001"
    networks:
      - proyectos-app
networks :
  proyectos-app :     